# Generated by Django 6.1.1 on 2026-09-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0003_savedphoto_savedshade'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedphoto',
            name='age_range',
            field=models.CharField(blank=True, choices=[('under_18', 'Di bawah 18'), ('18_24', '18–24'), ('25_34', '25–34'), ('35_plus', '35+')], max_length=20),
        ),
        migrations.AddField(
            model_name='savedphoto',
            name='nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='savedphoto',
            name='region',
            field=models.CharField(blank=True, choices=[('Jakarta', 'Jakarta'), ('West Java', 'Jawa Barat'), ('Central Java', 'Jawa Tengah'), ('East Java', 'Jawa Timur'), ('Sumatra', 'Sumatra'), ('Kalimantan', 'Kalimantan'), ('Sulawesi', 'Sulawesi'), ('Bali & Nusa Tenggara', 'Bali & Nusa Tenggara'), ('Papua', 'Papua')], max_length=50),
        ),
    ]
